INSERT INTO tb_category(name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Eletronics', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Home & Kitchen', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Toys & Games', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Clothing', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Shoes', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Sports & Outdoors', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Beauty & Personal Care', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Health & Household', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Grocery', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Pet Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Automotive', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Garden & Outdoors', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Office Products', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Interdimensional Banana Market', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Music', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Movies & TV', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Video Games', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Cell Phones & Accessories', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Jewelry', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Watches', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Baby Products', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Arts & Crafts', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Industrial & Scientific', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Luggage & Travel Gear', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Musical Instruments', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Collectibles & Fine Art', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Handmade', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Software', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Smart Home', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Furniture', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Lighting', NOW());